In [51]:
from numpy import *

In [52]:
seq="AUGGCAUCGGC"

In [79]:
def base_pair(i,j):

    pair = [seq[i], seq[j]]

    if pair == ['A','U'] or pair == ['U','A']:
        return(1)
    elif pair == ['C','G'] or pair == ['G','C']:
        return(1)
    else:
        return(0)

In [58]:
s = np.zeros([N, N])
fill_diagonal(s,0)

In [75]:
def score(seq,N):
  L=len(seq);
  s=zeros((L,L));
  for L in range(1,N):
    for i in range(0,N-L):
      j=i+L
      if j-i>=1:
        case1=s[i+1,j-1]+base_pair(i,j);
        case2=s[i+1,j];
        case3=s[i,j-1];
        case4=0;
        tmp=[];
        for k in range(i+1,j):
          tmp.append(s[i,k]+s[k+1,j]);
          case4=max(tmp);
        s[i,j]=max(case1,case2,case3,case4);
      else:
        s[i,j]=0
  return s;

In [76]:
def traceback(s, seq, i, j, pair):
    if i < j:
        if s[i, j] == s[i + 1, j - 1] + base_pair(i, j):
            pair.append([i, j, str(seq[i]), str(seq[j])])
            traceback(s, seq, i + 1, j - 1, pair)
        elif s[i, j] == s[i + 1, j]:
            traceback(s, seq, i + 1, j, pair)
        elif s[i, j] == s[i, j - 1]:
            traceback(s, seq, i, j - 1, pair)
        else:
            for k in range(i + 1, j):
                if s[i, j] == s[i, k] + s[k + 1, j]:
                    traceback(s, seq, i, k, pair)
                    traceback(s, seq, k + 1, j, pair)
                    break
    return pair


In [77]:
def run(seq):
    N=len(seq)
    s=score(seq, N)
    pair=traceback(s,seq,0,len(seq)-1,[])
    print(seq)
    print(s)


In [78]:
run(seq)

AUGGCAUCGGC
[[0. 1. 1. 1. 2. 2. 3. 4. 4. 4. 5.]
 [0. 0. 0. 0. 1. 2. 2. 3. 3. 3. 4.]
 [0. 0. 0. 0. 1. 1. 2. 3. 3. 3. 4.]
 [0. 0. 0. 0. 1. 1. 2. 2. 3. 3. 4.]
 [0. 0. 0. 0. 0. 0. 1. 1. 2. 3. 3.]
 [0. 0. 0. 0. 0. 0. 1. 1. 2. 2. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
